apiVersion: v1
kind: Service
metadata:
    labels:
        app: backend
    name: backend-service
spec:
    ports:
    - port: 8002
      protocol: TCP
      targetPort: 8002
      nodePort: 30007
    selector:
        app: backend
    type: NodePort