apiVersion: apps/v1
kind: Service
metadata:
    labels:
        app: react-app
    name: frontend-service
spec:
    ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      nodePort: 32000
    selector:
        app: react-app
    type: NodePort

