apiVersion: apps/v1

kind: Deployment

metadata:

  name: frontend-deployment

  labels:

    app: react-app

spec:

  replicas: 1

  selector:

    matchLabels:

      app: react-app

  template:

    metadata:

      labels:

        app: react-app

    spec:

      containers:

      - name: frontend

        image: s199/frontend

        ports:

        - containerPort: 3000

